name: MentionMe
version: 0.3.4
author: MoMoe
main: USA.MoMoe.MentionMe.Main

commands:
    mentionme:
        description: "Reloads the Config"
        usage: /mentionme
        permission: mentionme.reload
        permission-message: ยง4You don't have access to /mentionme.
permissions:
    mentionme.reload:
        default: op
        description: Gives the ability to reload the config.